# GET http://localhost:4004/odata/v4/product-shope/Product



# GET http://localhost:4004/odata/v4/product-shope/Supplier

# POST http://localhost:4004/odata/v4/product-shope/Product
# Content-Type: application/json


#     {
#       "name": "TATA Siara",
#       "brand": "TATA",
#       "price": 8934534999,
#       "category": "SUV"
#     }

#  GET http://localhost:4004/odata/v4/product-shope/Product?$expand=supplier


# GET http://localhost:4004/odata/v4/product-shope/Supplier?$expand=products
GET http://localhost:4004/odata/v4/product-shope/myFunc(name='Simranjit')